---
# tasks file for nc
- name: Start NC Service
  shell: >
    nohup {{ analytics_installdir }}/cbas/bin/cbasncservice -logdir {{ analytics_logdir }} < /dev/null > {{ analytics_logdir }}/ncservice.log 2>&1 &
  when: "not 'NCService' in jps_output.stdout"


