---
- block:
    - name: Download NoSQL Analytics Service for Couchbase {{ analytics_version }}
      get_url:
        url: http://packages.couchbase.com/releases/analytics/{{ analytics_version }}/couchbase-analytics-{{ analytics_version }}-generic.zip
        dest: "{{ analytics_installdir }}/couchbase-analytics-{{ analytics_version }}-generic.zip"
  rescue:
    - fail:
        msg: "http://packages.couchbase.com/releases/analytics/{{ analytics_version }}/couchbase-analytics-{{ analytics_version }}-generic.zip does not exist (do you need to specify a different analytics_version?)"  

- name: Unpack NoSQL Analytics Service for Couchbase
  unarchive:
    src: "{{ analytics_installdir }}/couchbase-analytics-{{ analytics_version }}-generic.zip"
    copy: no
    dest: "{{ analytics_installdir }}"
    creates: "{{ analytics_installdir }}/cbas/bin/cbasncservice"

