---
- name: Create analytics working directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ analytics_logdir }}"
    - "{{ analytics_installdir }}"
    - "{{ analytics_confdir }}"

- name: Check for local installation archive
  local_action: stat path=couchbase-analytics-{{ analytics_version }}-generic.zip
  register: local_archive
  become: no

- include: local_archive_{{ local_archive.stat.exists }}.yml

- name: Check analytics processes
  shell: jps
  register: jps_output

