---
- name: Create analytics working directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ analytics_logdir }}"
    - "{{ analytics_installdir }}"
    - "{{ analytics_confdir }}"

- name: Download and unpack NoSQL Analytics Service for Couchbase
  unarchive:
    src: couchbase-analytics-{{ cbas_version }}-generic.zip
    dest: "{{ analytics_installdir }}"
    creates: "{{ analytics_installdir }}/cbas/bin/cbasncservice"

- name: Check analytics processes
  shell: jps
  register: jps_output


