---
# tasks file for cc
- name: Download analytics config file
  template:
    src: analytics.conf
    dest: "{{ analytics_confdir }}"
  changed_when: False
  
- name: Start CC
  shell: >
    nohup {{ analytics_installdir }}/cbas/bin/cbascc -config-file {{ analytics_confdir }}/analytics.conf < /dev/null > {{ analytics_logdir }}/cc.log 2>&1 &
  when: "not 'CCDriver' in jps_output.stdout"

